/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.OGR {

public enum FieldDomainSplitPolicy {
  OFDSP_DEFAULT_VALUE,
  OFDSP_DUPLICATE,
  OFDSP_GEOMETRY_RATIO
}

}
